#!/bin/bash

# This script implements personalize as described
# here: https://coder.com/docs/coder-oss/latest/dotfiles#persistent-home.

set -e
pushd ~
if [ ! -d dotfiles ]; then
    git clone https://github.com/ammario/dotfiles
fi

sudo apt-get update
sudo apt-get install -y stow autojump redis fish rustc cargo neovim net-tools

sudo npm install -g n

pushd dotfiles
./install
