#!/bin/bash
if $(which apt >/dev/null); then
	sudo apt update
	sudo apt install -y neovim fish autojump dstat pg-activity stow cargo asciinema ncdu julia
fi

set -e

stow -t ~/.config/ .config/
stow git

# Install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Change default shell to fish.
sudo chsh -s $(which fish) $USER

# Install rust goodies
export CARGO_NET_GIT_FETCH_WITH_CLI=true
cargo install ripgrep killport
# exa, bat and typos-cli are already installed
